name: Auto Tag

on:
  push:
    branches:
      - main  # Replace with your default branch

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.26.0
      with:
        release_branches: main
        default_bump: patch
        tag_prefix: "v"
        major_pattern: 'major:'
        minor_pattern: 'minor:'
        patch_pattern: 'patch:'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
