name: Auto Tag

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Auto Bump Version
      uses: mathieudutour/github-tag-action@v5.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        create_annotated_tag: true
